CREATE TABLE `live_stream` (
   `id` varchar(36) NOT NULL,
   `created_at` timestamp NULL DEFAULT NULL,
   `updated_at` timestamp NULL DEFAULT NULL,
   `deleted_at` timestamp NULL DEFAULT NULL,
   `title` varchar(255) DEFAULT NULL,
   `type` int(11) DEFAULT NULL,
   `room_url` varchar(255) DEFAULT NULL,
   `description` text,
   `poster_url` varchar(255) DEFAULT NULL,
   `is_publish` tinyint(1) DEFAULT NULL,
   `start_at` timestamp NULL DEFAULT NULL,
   `end_at` timestamp NULL DEFAULT NULL,
   `post_video_url` varchar(255) DEFAULT NULL,
   `course_id` int(11) DEFAULT NULL,
   `teacher_id` int(11) DEFAULT NULL,
   `class_id` int(11) DEFAULT NULL,
   `live_stream_backup_url` varchar(255) DEFAULT NULL,
   `thumbnail_video` varchar(255) DEFAULT NULL,
   `is_on_air` tinyint(1) DEFAULT '0',
   `class_ids` varchar(255) DEFAULT NULL,
   `course_ids` varchar(255) DEFAULT NULL,
   `max_question_lobby` int(11) DEFAULT NULL,
   `room_id` varbinary(255) DEFAULT NULL,
   `push_notif` json DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;